export const movieGenres = [
  "Action",
  "Adventure",
  "Comedy",
  "Drama",
  "Horror",
  "Romance",
  "Science Fiction",
  "Fantasy",
  "Thriller",
  "Mystery",
  "Crime",
  "Animation",
  "Documentary",
  "Musical",
  "War",
  "Western",
  "Romantic Comedy",
  "Action Thriller",
  "Horror Comedy",
  "Superhero",
  "Post-Apocalyptic",
];
